### ISSUE TITLE
Implement Catalogue into Heron (GXP AddLayers, via W*S Capabilities)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [heron-mc/heron-mc#324] opened 2015-05-10 10:51 UTC
```
Implement a catalogue function to allow the user to pull layers from any of 
WMS/WFS/TMS/WMTS etc. Similar to http://suite.opengeo.org/geoexplorer/composer

* A implementer configurable button which can be added to the layers list that 
will allow users to add layers. [1]

* A separate button which will allow users to remove a selected layer from the 
layer list and the map. (already in layer-settings in a manner of speaking).

* The add-layers button should bring up a dialog/panel (which is better?) that 
includes a drop-down menu of all pre-configured systems. The bottom item on the 
list should be "Add new Server". [2]

*- The implementer can pre-configure services (probably with a "name", 
"description" as well as the URL) which will appear in a list.

*- Using the "Add new Server" item, the user is asked to enter a name and URL 
for the service. Once entered Heron will negotiate with the service invisibly. 
[3 (optional)]

*== It should support all of the following services at least: WMS, WMTS, TMS 
and WFS (the later can be styled by the user with the new tools after all). 
Other services too if desired ("anything supported by OpenLayers" was the 
quote).

*== Any service that is added by the user should be remembered in the drop-down 
list for future sessions (after browser restart), likely using cookies or HTML5 
storage.

*- Once a user has selected a service (implementer specified or user 
specified), Heron uses the GetCapabilities to list to the user the layers 
available. Layers should be listed alphabetically using the "Title" where 
available, or the "name" otherwise. The Abstract should be included somewhere 
too, along with any other pertinent information [4].

*- Above this layer list, heron will show the Service-wide title and abstract 
from the Getcapabilities.

*- This list of layers should be searchable (case insensitive). Ideally via a 
dynamic search box (similar to Google suggestions). It should search at least 
the title, but also keywords and maybe abstract too. [5 (optional)]

*- (WMS) For each layer there could be a small icon which should depict if a 
layer is queryable or not (WMS).

*- (WMS) How do we handle formats? Just assume PNG? Make the user select from 
available options using PNG as default?

*- (WMS) Where multiple styles are available, Heron should allow the user some 
way to specify which to use. [6 (optional)]

*- (WMS) Ideally it will include a preview of the style (the URL for the legend 
is in the GetCapabilities). I'd suggest only doing this if the legend 
width/height (also typically in getCaps) is below a certain threshold (though 
GeoServer currently has a bug where it mis-reports legend sizes).

*- User should be able to select multiple layers using standard Ctrl and Shift 
interface paradigms. [7]

*- Once a layer is added, it should be enabled by default on the map unless WFS 
(WFS would be off by default to stop accidental feature overload). [8]

* Any layers added should be remembered in the user's bookmarks if saved.

* Layers added later should be on top of layers added earlier.

* If a layer is added, Heron should use whatever the map projection is if the 
layer supports it. Otherwise use WGS:84 (always supported) and reproject. (that 
should cover everyone)

==============

The numbers is square brackets (i.e. [1]) are the order of actions I forsee a 
user taking.


Note: Due to the complexity of the UI for this feature, I'd *strongly* advise 
starting by creating a simple mockup of the proposed interface first and then 
liasing with us (and any other interested Heron devs/users) to confirm/tweak 
it. Alternately maybe 30 minutes with paint to knock up some screenshots may be 
an idea. I don't currently have any particular UI in mind, hence not providing 
any myself.
```

Original issue reported on code.google.com by `jonathan...@warwickshire.gov.uk` on 23 Dec 2013 at 1:55

**Comment by justb4** [comment] 2015-11-18 14:00
Inventory of the main outstanding problems for this issue, reproduced on http://kadviewer.kademo.nl

1. preconfigured TMS layers don't appear in "Toegevoegde Lagen" layertree Folder
2. remove layer button does not work as expected (seems to remove only last added layer)
3. same for "wrench" button 
4. including added layers in Bookmark produced disabled bookmark 

resolutions:
ad 1) let TMS Layers appear in Folder
ad 2) temp fix: enable Remove Layer button only for added layers (other layers don't make sense)
ad 3) temp fix: ditto (only newly added layers have (layer-)metadata from Capabilities)
ad 4) disable Bookmark adding with user message when added layers involved

After fixing these, we should close this issue and consider this Catalog-OWSServer ready and move to bugfixing mode with new (and smaller) issues.

**Comment by justb4** [comment] 2015-12-08 22:20
Fixed nr 2) and nr 3) above, try in in examples:

http://lib.heron-mc.org/heron/latest/examples/catalognl (catalog with Heron LayerTree)

http://lib.heron-mc.org/heron/latest/examples/catalog (catalog with native GXP layer container tree)

http://kadviewer.kademo.nl - full Heron example

**Comment by Ronald-Mulder** [comment] 2015-12-10 15:07
My first impression is very good, nice work!
I would like to do a bit more testing though.
Is the 'wrench' tool significantly different to get to work on the active layer? The opacity tool seems to work fine...

**Comment by justb4** [comment] 2015-12-10 16:14
Thanks! 
The 'wrench' tool : only (WMS) Layers added via the Catalog have metadata (like abstract, image formats, styles etc) from the WMS Capabilities to fill out all/most forms in the wrench popup. 'Normal' Layers, added via the Heron config in the layertree, don't have all this metadata, so the wrench popup becomes meaningless/confusing. TMS-Layers have no metadata at all. A possible fix would be to have a more minimal wrench popup in these cases.  Some viewers are driven entirely by Catalog...

**Comment by Ronald-Mulder** [comment] 2015-12-22 15:30
Hi Just,
Sorry it took awhile but I have tested some more.
I found some strange behaviour when adding layers from a CSW. The layers are added many times, it looks like a TMS(?) is added and each tile is a new layer with the same name? Also there seems to be a mouseover event of some sorts which hides the above mentioned layers. Sorry for my probably poor description... Does the above sound familiar? The CSW functions is only usefull in a small part this way. Please let me know what you think, no great hurry however being the holidays season and all.

**Comment by justb4** [comment] 2015-12-23 16:22
Adding Layers from a (public) CSW like NGR has some pecularities. This mostly has to do with a) how metadata is entered b) (OGC/OSGeo)-compliancy of found services (WMS/WFS).

Ad a) some metadata records have 10-s, sometimes even 100-s of Layers configured, see example figure for "CBS Bevolkingskernen" and its MD: http://www.nationaalgeoregister.nl/geonetwork/srv/dut/search?#|5ab673ad-b462-4e4a-80f4-8aae62ada030
![ngr-csw-multilayer](https://cloud.githubusercontent.com/assets/582630/11979963/b3c9ccd8-a997-11e5-94ed-8ba58f8a5ced.jpg)
The effect (now) is that you get all those layers added as the GXP widget is now used "as-is".
ANother example is when you look for "Zeegraskartering".

Ad b) many services are not WMS/WFS-compliant, especially from ESRI servers. For example GetFeatureInfo and GetLegendGraphic will not work as expected.

If the CSW and its services is under your own control than you may not get unexpected results.

Note: that your issue is with the CSW-"Catalog" function. This is implemented via another issue #400. This issue is about the preconfigured catalog variant.

**Comment by dracic** [comment] 2015-12-23 19:06
I think it won't be possible to catch all possibilities and think in best scenario catalog should be able to add layer when there is only one layer listed in metadata and if its url can be parsed this way:

prefix?service=W[M,F]S&layer=*
prefix/W[M,S]?layer=*

(possibly TMS and WMTS)

That is my workaround (WMS for now), otherwise I tell users to explore metadata and add service manually...

Or if only url of service can be parsed (somehow) add layer window could pop up instead of hiding add button?

**Comment by Ronald-Mulder** [comment] 2016-01-06 09:13
@justb4: in the Gasunie context I would like for you to incorporate the current functionality in a Heron build. This way we can do further testing in-house.

**Comment by justb4** [comment] 2016-01-06 10:11
On 06-01-16 10:13, Ronald-Mulder wrote:
> @justb4 <https://github.com/justb4>: in the Gasunie context I would like
> for you to incorporate the current functionality in a Heron build. This
> way we can do further testing in-house.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/heron-mc/heron-mc/issues/324#issuecomment-169272786>.
>
You can always download the latest Heron build called "Heron Unstable" 
from: http://lib.heron-mc.org/heron/latest/heron-unstable.zip
(or via Heron Downloads http://heron-mc.org/downloads.html) This build 
is always triggered from a Git commit/push so reflects the Heron GH 
version. Let me know if this works for you.

**Comment by justb4** [comment] 2016-02-11 21:01
Main functionality implemented/working, now into maintenance mode via new issues.

**Closed by justb4** 2016-02-11 21:01 UTC
Labels: auto-migrated, Milestone-Release1.0.3, Priority-Medium, Project-Warwick-Ph2, Type-Enhancement
